In [171]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import GridSearchCV
%matplotlib inline 

In [197]:
#data = pd.ExcelFile()
data = pd.read_excel('Earthquake Damage Data.xlsx', 'Data')
data

ID        P1        P2        P3        P4    P5        P6  \
0          1  0.733800  0.588313  0.824660  0.420993  0.00  0.599542   
1          2  0.738113  0.604497  0.477239  0.252442  0.75  0.544622   
2          3  0.742815  0.602485  0.755395  0.434462  0.75  0.560641   
3          4  0.739635  0.602389  0.768629  0.484940  0.75  0.556064   
4          5  0.740052  0.605121  0.783227  0.486592  0.75  0.542334   
...      ...       ...       ...       ...       ...   ...       ...   
30585  30598  0.339535  0.427073  0.891602  0.612456  0.00  0.606407   
30586  30599  0.365588  0.466539  0.806961  0.635176  0.00  0.501144   
30587  30600  0.290186  0.357288  0.889132  0.606094  0.00  0.718535   
30588  30601  0.281798  0.346521  0.985965  0.512369  0.00  0.727689   
30589  30602  0.330911  0.400206  0.947815  0.577603  0.00  0.713959   

            BC1  BC2  BC3  BC4  BC5  BC6       BC7       BC8  DS  
0      0.257812    0  0.0    0  0.8  1.0  0.000000  0.827586   4  
1      0.148438    0  0.0    1  0.8  1.0  0.666667  0.931034   1  
2      0.093750    1  1.0    1  0.8  1.0  0.000000  0.655172   1  
3      0.148438    0  0.0    0  0.8  1.0  0.000000  0.965517   1  
4      0.148438    0  0.0    1  0.8  0.5  0.666667  0.931034   1  
...         ...  ...  ...  ...  ...  ...       ...       ...  ..  
30585  0.281250    1  0.0    0  0.8  0.5  0.000000  1.000000   1  
30586  0.078125    1  0.0    0  1.0  1.0  1.000000  1.000000   1  
30587  0.078125    1  0.0    0  0.4  1.0  0.000000  0.827586   1  
30588  0.078125    1  0.0    0  0.4  1.0  0.000000  0.827586   1  
30589  0.078125    1  0.0    0  0.4  0.5  0.000000  1.000000   1  

[30590 rows x 16 columns]

In [174]:
#x = data.iloc[:,[1,2,3,4,5,6]].values
#y = data.iloc[:,[7,8,9,10,11,12,13,14]].values
#z = data.iloc[:,15].values
x = data.iloc[:,[1,2,3,4,5,6,7,8,9,10,11,12,13,14]].values
y = data.iloc[:,15].values


In [237]:
#x_train, x_test, y_train, y_test, z_train, z_test= train_test_split(x,y,z,test_size=0.25,random_state=0)
x_train, x_test, y_train, y_test= train_test_split(x,y,test_size=0.2,random_state=0)

In [239]:
sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.transform(x_test)
#sc_y=StandardScaler()
#y_train=sc_y.fit_transform(y_train)
#y_test=sc_y.transform(y_test)

In [241]:
#classifier = KNeighborsClassifier(n_neighbors = 2, metric = 'minkowski', p=2)
classifier = KNeighborsClassifier(n_neighbors = 2)
classifier.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=2)

In [243]:
y_pred = classifier.predict(x_test)

In [245]:
cm=confusion_matrix(y_test, y_pred)
cm

array([[5426,    4,   11,   89],
       [  24,    1,    0,    1],
       [  24,    0,    1,    0],
       [ 485,    0,    4,   48]], dtype=int64)

In [247]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.8950637463223275

Classification Report:
               precision    recall  f1-score   support

           1       0.91      0.98      0.94      5530
           2       0.20      0.04      0.06        26
           3       0.06      0.04      0.05        25
           4       0.35      0.09      0.14       537

    accuracy                           0.90      6118
   macro avg       0.38      0.29      0.30      6118
weighted avg       0.85      0.90      0.87      6118


Confusion Matrix:
 [[5426    4   11   89]
 [  24    1    0    1]
 [  24    0    1    0]
 [ 485    0    4   48]]


In [211]:
classifier.score(x_test,y_test)

0.8955722639933166