In [264]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import GridSearchCV
import sklearn
from sklearn.linear_model import LinearRegression
import seaborn as sns
%matplotlib inline 

In [265]:
#data = pd.ExcelFile()
data = pd.read_excel('Earthquake Damage Data.xlsx', 'Data')
data.head()

ID        P1        P2        P3        P4    P5        P6       BC1  BC2  \
0   1  0.733800  0.588313  0.824660  0.420993  0.00  0.599542  0.257812    0   
1   2  0.738113  0.604497  0.477239  0.252442  0.75  0.544622  0.148438    0   
2   3  0.742815  0.602485  0.755395  0.434462  0.75  0.560641  0.093750    1   
3   4  0.739635  0.602389  0.768629  0.484940  0.75  0.556064  0.148438    0   
4   5  0.740052  0.605121  0.783227  0.486592  0.75  0.542334  0.148438    0   

   BC3  BC4  BC5  BC6       BC7       BC8  DS  
0  0.0    0  0.8  1.0  0.000000  0.827586   4  
1  0.0    1  0.8  1.0  0.666667  0.931034   1  
2  1.0    1  0.8  1.0  0.000000  0.655172   1  
3  0.0    0  0.8  1.0  0.000000  0.965517   1  
4  0.0    1  0.8  0.5  0.666667  0.931034   1

In [266]:
x = data.iloc[:,[1,2,3,4,5,6,7,8,9,10,11,12,13,14]].values
y = data.iloc[:,15].values
print (x.shape)
print (y.shape)

(30590, 14)
(30590,)


In [267]:
x_train, x_test, y_train, y_test= train_test_split(x,y,test_size=0.2,random_state=0)

In [268]:
sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.transform(x_test)

## KNN

In [269]:
model_KNN = KNeighborsClassifier(n_neighbors = 2)
model_KNN.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=2)

In [270]:
y_pred_KNN = model_KNN.predict(x_test)

In [271]:
cm=confusion_matrix(y_test, y_pred_KNN)
print("Accuracy:", accuracy_score(y_test, y_pred_KNN))
print("\nClassification Report:\n", classification_report(y_test, y_pred_KNN))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_KNN))

Accuracy: 0.8950637463223275

Classification Report:
               precision    recall  f1-score   support

           1       0.91      0.98      0.94      5530
           2       0.20      0.04      0.06        26
           3       0.06      0.04      0.05        25
           4       0.35      0.09      0.14       537

    accuracy                           0.90      6118
   macro avg       0.38      0.29      0.30      6118
weighted avg       0.85      0.90      0.87      6118


Confusion Matrix:
 [[5426    4   11   89]
 [  24    1    0    1]
 [  24    0    1    0]
 [ 485    0    4   48]]


# SVM

In [272]:
model_SVM = svm.SVC(kernel='linear')
model_SVM.fit(x_train, y_train)

SVC(kernel='linear')

In [273]:
y_pred_SVM = model_SVM.predict(x_test)
print("Accuracy:", accuracy_score(y_test, y_pred_SVM))
print("\nClassification Report:\n", classification_report(y_test, y_pred_SVM))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_SVM))

Accuracy: 0.9038901601830663

Classification Report:
               precision    recall  f1-score   support

           1       0.90      1.00      0.95      5530
           2       0.00      0.00      0.00        26
           3       0.00      0.00      0.00        25
           4       0.00      0.00      0.00       537

    accuracy                           0.90      6118
   macro avg       0.23      0.25      0.24      6118
weighted avg       0.82      0.90      0.86      6118


Confusion Matrix:
 [[5530    0    0    0]
 [  26    0    0    0]
 [  25    0    0    0]
 [ 537    0    0    0]]


d:\anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


# linear regression

In [274]:
model_lr = LinearRegression()
model_lr.fit(x_train, y_train)
y_pred_lr = model_lr.predict(x_test)
print("预测值示例:", y_pred_lr[:5])

预测值示例: [1.50029269 1.26187122 1.18266208 1.29743236 1.47511701]


#### 预测值是分数（连续数值），而不是离散的类别标签 ​线性回归模型（LinearRegression）​，而线性回归是专门用于解决 ​回归任务 的模型（预测连续值）

In [275]:

# print("Accuracy:", accuracy_score(y_test, y_pred_lr))
# print("\nClassification Report:\n", classification_report(y_test, y_pred_lr))
# print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_lr))

# logistic regression

In [276]:
from sklearn.linear_model import LogisticRegression
model_lg = LogisticRegression(multi_class='multinomial', max_iter=1000)
model_lg.fit(x_train, y_train)
y_pred_lg = model_lg.predict(x_test)
print("Accuracy:", accuracy_score(y_test, y_pred_lg))
print("\nClassification Report:\n", classification_report(y_test, y_pred_lg))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_lg))

Accuracy: 0.9038901601830663

Classification Report:
               precision    recall  f1-score   support

           1       0.90      1.00      0.95      5530
           2       0.00      0.00      0.00        26
           3       0.00      0.00      0.00        25
           4       0.00      0.00      0.00       537

    accuracy                           0.90      6118
   macro avg       0.23      0.25      0.24      6118
weighted avg       0.82      0.90      0.86      6118


Confusion Matrix:
 [[5530    0    0    0]
 [  26    0    0    0]
 [  25    0    0    0]
 [ 537    0    0    0]]


d:\anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
d:\anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill

# Naive bayes

In [277]:
from sklearn.naive_bayes import GaussianNB
model_nv = GaussianNB()
model_nv.fit(x_train, y_train)
y_pred_nv = model_nv.predict(x_test)
print("Accuracy:", accuracy_score(y_test, y_pred_nv))
print("\nClassification Report:\n", classification_report(y_test, y_pred_nv))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_nv))

Accuracy: 0.5084995096436744

Classification Report:
               precision    recall  f1-score   support

           1       0.91      0.53      0.67      5530
           2       0.01      0.96      0.02        26
           3       0.01      0.04      0.02        25
           4       0.17      0.24      0.20       537

    accuracy                           0.51      6118
   macro avg       0.28      0.44      0.23      6118
weighted avg       0.83      0.51      0.63      6118


Confusion Matrix:
 [[2955 1891   67  617]
 [   1   25    0    0]
 [  13    8    1    3]
 [ 296  104    7  130]]


# Decision tree

In [278]:
from sklearn.tree import DecisionTreeClassifier
model_DT = DecisionTreeClassifier(
    random_state=42,
    class_weight='balanced'  # 自动平衡类别权重
)
model_DT.fit(x_train, y_train)
y_pred_DT = model_DT.predict(x_test)
print("Accuracy:", accuracy_score(y_test, y_pred_DT))
print("\nClassification Report:\n", classification_report(y_test, y_pred_DT))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_DT))

Accuracy: 0.8592677345537757

Classification Report:
               precision    recall  f1-score   support

           1       0.92      0.92      0.92      5530
           2       0.04      0.04      0.04        26
           3       0.00      0.00      0.00        25
           4       0.28      0.26      0.27       537

    accuracy                           0.86      6118
   macro avg       0.31      0.31      0.31      6118
weighted avg       0.86      0.86      0.86      6118


Confusion Matrix:
 [[5114   23   31  362]
 [  24    1    1    0]
 [  23    1    0    1]
 [ 387    0    8  142]]


# ANN(MLP)

In [279]:
from sklearn.neural_network import MLPClassifier
model_MLP = MLPClassifier(
    hidden_layer_sizes=(50, 20),  # 隐藏层结构
    activation='relu',
    solver='adam',
    max_iter=200,
    random_state=42
)
model_MLP.fit(x_train, y_train)
y_pred_MLP = model_MLP.predict(x_test)
print("Accuracy:", accuracy_score(y_test, y_pred_MLP))
print("\nClassification Report:\n", classification_report(y_test, y_pred_MLP))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_MLP))

Accuracy: 0.9037267080745341

Classification Report:
               precision    recall  f1-score   support

           1       0.91      0.99      0.95      5530
           2       0.00      0.00      0.00        26
           3       0.00      0.00      0.00        25
           4       0.50      0.10      0.16       537

    accuracy                           0.90      6118
   macro avg       0.35      0.27      0.28      6118
weighted avg       0.87      0.90      0.87      6118


Confusion Matrix:
 [[5477    0    2   51]
 [  26    0    0    0]
 [  25    0    0    0]
 [ 485    0    0   52]]


d:\anaconda\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
d:\anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicte

# CNN

In [280]:
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models, regularizers
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

# 构建 1D-CNN 模型
model_CNN = models.Sequential([
    layers.Conv1D(32, kernel_size=3, activation='relu', 
                  kernel_regularizer=regularizers.l2(0.001),
                  input_shape=(14, 1)),
    layers.MaxPooling1D(pool_size=2),
    layers.Dropout(0.3),
    layers.Conv1D(64, kernel_size=3, activation='relu'),
    layers.MaxPooling1D(pool_size=2),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(10, activation='softmax')
])

model_CNN.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# 训练
history = model_CNN.fit(
    x_train, y_train,
    epochs=30,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

# 预测与评估
y_pred_CNN = model_CNN.predict(x_test)
y_pred_CNN = np.argmax(y_pred_CNN, axis=1)

print("Accuracy:", accuracy_score(y_test, y_pred_CCN))
print("\nClassification Report:\n", classification_report(y_test, y_pred_CCN))


d:\anaconda\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/30
612/612 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8770 - loss: 0.5899 - val_accuracy: 0.9032 - val_loss: 0.3541
Epoch 2/30
612/612 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9072 - loss: 0.3608 - val_accuracy: 0.9032 - val_loss: 0.3480
Epoch 3/30
612/612 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9044 - loss: 0.3544 - val_accuracy: 0.9032 - val_loss: 0.3461
Epoch 4/30
612/612 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9049 - loss: 0.3556 - val_accuracy: 0.9032 - val_loss: 0.3437
Epoch 5/30
612/612 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9066 - loss: 0.3407 - val_accuracy: 0.9032 - val_loss: 0.3416
Epoch 6/30
612/612 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9071 - loss: 0.3384 - val_accuracy: 0.9032 - val_loss: 0.3419
Epoch 7/30
612/612 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.9080 - loss: 0.3356 - val_accuracy: 0.9032 - val_loss: 0.3376
Epoch 8/30
612/612 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.9046 - loss: 0.3418 - val_accuracy: 0

d:\anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
